// DO NOT EDIT THIS FILE!
// Add necessary tools in the `tools.ts` file.

import process from 'node:process'
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js'
import express from 'express'
import { registerTools } from './tools'

const server = new McpServer({
  name: 'mcp-server',
  version: '1.0.0',
})

registerTools(server)

const app = express()
app.use(express.json())

app.post('/mcp', async (req, res) => {
  const transport = new StreamableHTTPServerTransport({
    sessionIdGenerator: undefined,
    enableJsonResponse: true,
  })

  res.on('close', () => {
    transport.close()
  })

  await server.connect(transport)
  await transport.handleRequest(req, res, req.body)
})

const port = process.env.PORT ? parseInt(process.env.PORT) : 8001
app
  .listen(port, () => {
    console.log(`MCP Server running on http://localhost:${port}/mcp`)
  })
  .on('error', (error) => {
    console.error('Server error:', error)
    process.exit(1)
  })
